# Generated by Django 2.2 on 2019-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ultima_alteracao',
            field=models.DateTimeField(null=True),
        ),
    ]
